package telran.security.dto;

public enum ResponseCode {

	USERNAME_EXIST, PASSWORD_INCORRECT, OK, PASSWORD_SHOULD_NOT_REPEAT_PREVIOUS_3_PASSWORDS, 
	NO_USERNAME, ROLE_EXIST, ROLE_NO_EXIST, OKK, ACCOUNT_NO_ACTIVE, ACCOUNT_NOT_REVOKE;
}
